[package]
name = "pypilot"
version = "0.4.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
colored = "3.0.0"
tokio = { version = "1.47.1", features = ["full"] }
config = "0.15.16"
serde = { version = "1.0.226", features = ["derive"] }
once_cell = "1.21.3"
serde_path_to_error = "0.1.20"
shellexpand = "3.1.1"
which = "8.0.0"
