name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update rustc
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: make package
    - name: Run tests
      run: make test
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-binary
        path: dist

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: make package
    - name: Run tests
      run: make test
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-binary
        path: dist
