name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release --target x86_64-unknown-linux-musl
    #- name: Run tests
    #  run: cargo test --verbose
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-binary
        path: target/release/manage-python

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-binary
        path: target/release/manage-python.exe
